title: nikkibarry.github.io
domain: nikkibarry.github.io    
url: "https://nikkibarry.github.io" 

collections:
  mainpages:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "mainpages"
    values:
      layout: "page"


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag